development:
  adapter: postgresql
  encoding: unicode
  database: leaf_farm_demo_dev
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: carltonlasiter

test:
  adapter: postgresql
  encoding: unicode
  database: leaf_farm_demo_test
  pool: 5
  host: localhost
  port: 5432
  username: postgres
  password: carltonlasiter

production:
  adapter: postgresql
  encoding: unicode
  database: leaf_farm_demo_production
  pool: 5
  password:
